#ifndef UTILS_DATA_PATH_HPP_
#define UTILS_DATA_PATH_HPP_
//========================================================================================
// AthenaXXX astrophysical plasma code
// Copyright(C) 2020 James M. Stone <jmstone@ias.edu> and the Athena code team
// Licensed under the 3-clause BSD License (the "LICENSE")
//========================================================================================
//! \file data_path.hpp
//! \brief where a data file a deck names is found.  The tables the table readers load
//! (opacity, LTE/Saha EOS, CompOSE, TOV) are generated by scripts and kept out of git, in
//! a data directory: $ATHENAK_DATA when it is set, else <source tree>/data.

#include <string>

//! The file a deck names as `name`.  An absolute path is returned as it is.  A relative
//! one is taken relative to the working directory when such a file exists there (the
//! behaviour every existing deck relies on), else under $ATHENAK_DATA, else under
//! <source tree>/data; the first that exists is returned.  When none does, `name` comes
//! back unchanged, so the caller's open fails on the name the deck gave, and *searched
//! (if given) lists the places tried, for the caller's message.
std::string ResolveDataPath(const std::string &name, std::string *searched = nullptr);

#endif  // UTILS_DATA_PATH_HPP_
